name: Robot Framework CI

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Robot Tests
        run: robot tests/
        
#Step 6 > Viewing Reports
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-report
          path: report.html

