name: Robot Framework CI

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      #- name: Run Robot Tests
       # run: robot tests/

      - name: Run Robot Tests
        run: robot -i Smoke tests/ # -i ဆိုတာ include (ထည့်သွင်းရန်) လို့ အဓိပ္ပာယ်ရပါတယ်။

# Chrome Driver ကို စက်ထဲမှာ အသင့်ဖြစ်အောင် လုပ်ပေးတာ
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
#Step 6 > Viewing Reports
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-report
          path: report.html



